language: cpp

dist: trusty

compiler:
  - clang
  - gcc

env:
  global:
    - OPENCV_VERSION=3.2.0
    - OPENCV_INSTALL_DIR="$HOME/opencv-$OPENCV_VERSION-install"
    - G2O_INSTALL_DIR="$HOME/g2o-install"
    - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$OPENCV_INSTALL_DIR/lib"
    - PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$OPENCV_INSTALL_DIR/lib/pkgconfig"
    - PYTHONPATH="$OPENCV_INSTALL_DIR/lib/python3.6/site-packages"

cache:
  directories:
    - $OPENCV_INSTALL_DIR
  pip: true
  apt: true

before_install:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update

install:
  # install deps
  - sudo apt-get install -y libopencv-dev libeigen3-dev libpcl-all libsuitesparse-dev
  - ./.install-opencv.sh
  # manual build and install of g2o
  - git submodule init
  - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$OPENCV_INSTALL_DIR
  - ./.install-g2o.sh

script:
  - mkdir build && cd build
  - export G2O_ROOT=$G2O_INSTALL_DIR
  - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH
  - cmake ..
  - make
