language: cpp

dist: trusty

compiler:
  - clang
  - gcc

cache:
  directories:
    - $OPENCV_INSTALL_DIR
  pip: true

env:
  global:
    - OPENCV_VERSION=3.2.0
    - OPENCV_INSTALL_DIR="$HOME/opencv-$OPENCV_VERSION-install"
    - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$OPENCV_INSTALL_DIR/lib"
    - PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$OPENCV_INSTALL_DIR/lib/pkgconfig"
    - PYTHONPATH="$OPENCV_INSTALL_DIR/lib/python3.6/site-packages"

before_install:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update

install:
  # install deps
  - sudo apt-get install -y libopencv-dev libeigen3-dev libpcl-all
  - ./.install-opencv.sh
  # manual build and install of g2o
  - git submodule init
  - cd g2o
  - mkdir build && cd build
  - cmake ..
  - sudo make install

script:
  - cd ../../
  - mkdir build && cd build && cmake ..
  - make
