language: cpp

dist: trusty

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update
  # install deps
  - sudo apt-get install -y libopencv3-dev libeigen3-dev libpcl-all
  # manual build and install of g2o
  - git submodule init
  - cd g2o
  - mkdir build && cd build
  - cmake ..
  - sudo make install

script:
  - cd ../../
  - mkdir build && cd build && cmake ..
  - make
