language: cpp

dist: trusty

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get --qq update
  # install deps
  - sudo apt-get install -y libopencv-dev libeigen-dev libpcl-dev
  # manual build and install of g2o
  - git submodule init
  - cd g2o
  - mkdir build && cd build
  - cmake ..
  - sudo make install

script:
  - cd ../../
  - mkdir build && cd build && cmake ..
  - make
